//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLLEGEUSER
    {
        public COLLEGEUSER()
        {
            this.COLLEGEUSERCLAIMS = new HashSet<COLLEGEUSERCLAIMS>();
            this.COLLEGEUSERLOGINS = new HashSet<COLLEGEUSERLOGINS>();
            this.COLLEGEUSERROLE = new HashSet<COLLEGEUSERROLE>();
        }
    
        public int COLLEGEUSERID { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string USERNAME { get; set; }
    
        public virtual ICollection<COLLEGEUSERCLAIMS> COLLEGEUSERCLAIMS { get; set; }
        public virtual ICollection<COLLEGEUSERLOGINS> COLLEGEUSERLOGINS { get; set; }
        public virtual ICollection<COLLEGEUSERROLE> COLLEGEUSERROLE { get; set; }
    }
}
