//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COLLEGEROLE
    {
        public COLLEGEROLE()
        {
            this.COLLEGEUSERROLE = new HashSet<COLLEGEUSERROLE>();
        }
    
        public int COLLEGEROLEID { get; set; }
        public string ROLENAME { get; set; }
    
        public virtual ICollection<COLLEGEUSERROLE> COLLEGEUSERROLE { get; set; }
    }
}
